name: shot_call
description: "Party App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2
  get_it: ^7.7.0
  injectable: ^2.4.0
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.1.2
  connectivity_plus: ^6.0.3
  avatar_glow: ^3.0.1
  device_preview: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  very_good_analysis: ^5.1.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
